name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - kind: linux
            platform: amd64
            abi: glibc
            runner: ubuntu-24.04
          - kind: linux
            platform: amd64
            abi: musl
            runner: ubuntu-24.04
          - kind: linux
            platform: arm64
            abi: glibc
            runner: ubuntu-24.04-arm
          - kind: linux
            platform: arm64
            abi: musl
            runner: ubuntu-24.04-arm
          - kind: macos
            arch: arm64
            runner: macos-14
          - kind: macos
            arch: x86_64
            runner: macos-14

    steps:
      - uses: actions/checkout@v6

      - name: Precompile and test
        if: matrix.kind == 'linux'
        uses: dagger/dagger-for-github@v8.4.1
        with:
          version: 0.21.6
          args: >-
            ci \
              --ref pull/${{ github.ref_name }} \
              --platform-name linux/${{ matrix.platform }} \
              --abi ${{ matrix.abi }} \
            export \
              --path . \
              --allowParentDirPath

      - name: Build
        if: matrix.kind == 'macos'
        run: |
          pushd custom
          ./build-for-mac.sh macos ${{ matrix.arch }} 29.0.2
          popd

      - name: Upload files
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.kind }}-${{ matrix.platform || matrix.arch }}-${{ matrix.abi || 'default' }}
          path: |
            pdfium-nif-*
            custom/pdfium-nif-*
