name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - stable

jobs:
  build-for-linux:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        abi:
          - glibc
          - musl
        platform:
          - arm64
          - amd64

    steps:
      - uses: actions/checkout@v3

      - name: Precompile and test
        uses: dagger/dagger-for-github@v7.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          version: 0.15.1
          args: >-
            ci \
              --ref pull/${{ github.ref_name }} \
              --platform-name linux/${{ matrix.platform }} \
              --abi ${{ matrix.abi }} \
              --github-token GITHUB_TOKEN \
            export \
              --path . \
              --allowParentDirPath

      - name: Upload files
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.abi }}
          path: pdfium-nif-*

  build-for-macos:
    runs-on: macos-14
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          pushd custom
          ./build-for-mac.sh macos arm64 27.2
          ./build-for-mac.sh macos x86_64 27.2
          popd

      - name: Upload files
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        uses: actions/upload-artifact@v4
        with:
          name: macOS-builds
          path: custom/pdfium-nif-*

  update-checksums:
    runs-on: ubuntu-24.04

    needs:
      - build-for-linux
      - build-for-macos

    steps:
      - uses: actions/checkout@v3

      - name: Precompile and test
        uses: dagger/dagger-for-github@v7.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          version: 0.15.1
          args: >-
            update-checksums \
              --pr ${{ github.event.pull_request.number }} \
              --actor ${{ github.actor }} \
              --github-token GITHUB_TOKEN
