name: Post Merge Actions

on:
  pull_request:
    types: [closed]

jobs:
  post_merge:
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug info
        run: |
          echo "PR Branch name: ${{ github.event.pull_request.head.ref }}"
          echo "Base Branch: ${{ github.event.pull_request.base.ref }}"
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "Merge commit: ${{ github.sha }}"

      - name: Create files
        run: |
          mkdir artifacts
          echo "Merged from: ${{ github.event.pull_request.head.ref }}" > artifacts/branch_info.txt
          echo "PR #${{ github.event.pull_request.number }}" > artifacts/pr_info.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: post-merge-${{ github.event.pull_request.number }}
          path: artifacts/
