name: Post Merge Actions

on:
  pull_request:
    types: [closed]

jobs:
  post_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get workflow run
        uses: actions/github-script@v7
        id: get-workflow-run
        with:
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'test-uploads.yaml',
              branch: context.payload.pull_request.head.ref,
              status: 'success',
              per_page: 1
            });
            if (runs.data.workflow_runs.length === 0) {
              throw new Error('No successful workflow runs found');
            }
            return runs.data.workflow_runs[0].id;

      - name: Download artifacts from test workflow
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.get-workflow-run.outputs.result }}
          pattern: '*'
          path: release-artifacts
          repository: ${{ github.repository }}

      - name: Create Release with Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            "release-${{ github.event.pull_request.number }}-${{ github.run_number }}" \
            --title "Release $(date +'%Y-%m-%d')" \
            --notes "Automated release from PR #${{ github.event.pull_request.number }}" \
            release-artifacts/**/*
