name: Post Merge Actions

on:
  pull_request:
    types: [closed]

jobs:
  post_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts from test workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the run ID of the latest successful test-uploads workflow from this PR's branch
          RUN_ID=$(gh run list \
            --workflow test-uploads.yaml \
            --branch ${{ github.event.pull_request.head.ref }} \
            --status success \
            --limit 1 \
            --json databaseId \
            --repo gmile/pdfium \
            --jq '.[0].databaseId')

          # Download all artifacts from that run
          gh run download $RUN_ID --repo gmile/pdfium

      - name: Create Release with Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            "release-${{ github.event.pull_request.number }}-${{ github.run_number }}" \
            --title "Release $(date +'%Y-%m-%d')" \
            --repo gmile/pdfium \
            --notes "Automated release from PR #${{ github.event.pull_request.number }}" \
            *
