name: precompile

on:
  push:

jobs:
  linux:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        libc:
          - glibc
          - musl
        platform:
          - linux/arm64
          - linux/amd64

    steps:
      - uses: actions/checkout@v3
      - run: mkdir output
      - name: Precompile
        uses: dagger/dagger-for-github@v6
        with:
          version: 0.15.1
          args: >-
            precompile --libc ${{ matrix.libc }} --c-src-dir c_src --build-scripts-src-dir custom --plat ${{ matrix.platform }}
            export --path output/ --allowParentDirPath
