name: ci

# Call workflow manually
#
# TODO: make release verified
#
# TODO: have custom cc_precompiler according to rules here:
#
# TODO: rename pdfium-tag -> libpdfium-tag
#
# TODO: add macos build
#
# TODO: add hexpm release here
#
#       mix hex.publish package
#       mix hex.user auth
#       mix hex.publish package --yes --replace ???
#
# TODO: add tailscale to GH runners

# Test:
#
#   1. push "1" to stable branch
#
#   2. run wf to bump pdfium
#
#   3. expect it to finish CI as green and get merged automatically

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  linux:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        abi:
          - glibc
          - musl
        platform:
          - linux/arm64
          - linux/amd64

    steps:
      - uses: actions/checkout@v3

      - name: Precompile and test
        uses: dagger/dagger-for-github@v7.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 0.15.1
          args: >-
            ci \
              --ref ${{ github.ref_name }} \
              --platform-name ${{ matrix.platform }} \
              --abi ${{ matrix.abi }} \
              --github-token GITHUB_TOKEN
