name: precompile

on:
  push:
    tags:
      - 'v*'

jobs:
  linux:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        pdfium-tag:
          - chromium/6886
        abi:
          - glibc
          - musl
        platform:
          - linux/arm64
          - linux/amd64

    steps:
      - uses: actions/checkout@v3

      - run: mkdir output

      - name: Precompile
        uses: dagger/dagger-for-github@v7.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 0.15.1
          args: >-
            build-test-and-publish \
              --tag v0.1.0 \
              --abi ${{ matrix.abi }} \
              --src-dir c_src \
              --platform-name ${{ matrix.platform }} \
              --pdfium-tag chromium/6886 \
              --github-token GITHUB_TOKEN \
              sync
          engine-stop: false
