name: precompile

on:
  push:
    tags:
      - 'v*'

jobs:
  linux:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        pdfium_tag:
          - chromium/6886
        abi:
          - glibc
          - musl
        platform:
          - linux/arm64
          - linux/amd64

    steps:
      - uses: actions/checkout@v3

      - name: Create release draft
        uses: dagger/dagger-for-github@v7.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 0.15.1
          args: create-release --tag ${{ github.ref_name }} --draft=true --github-token GITHUB_TOKEN sync
          engine-stop: false

      - name: Precompile
        uses: dagger/dagger-for-github@v7.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 0.15.1
          args: >-
            build-test-and-publish \
              --tag ${{ github.ref_name }} \
              --abi ${{ matrix.abi }} \
              --src-dir c_src \
              --platform-name ${{ matrix.platform }} \
              --pdfium-tag ${{ matrix.pdfium_tag }} \
              --github-token GITHUB_TOKEN \
              sync

      - name: Publish release draft
        uses: dagger/dagger-for-github@v7.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 0.15.1
          args: edit-release --tag ${{ github.ref_name }} --draft=false --github-token GITHUB_TOKEN sync
          engine-stop: false

      # TODO: add hexpm release here
      #
      #       mix hex.publish package
      #       mix hex.user auth
      #       mix hex.publish package --yes --replace ???
