name: precompile

on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Precompile
        uses: dagger/dagger-for-github@v6
        with:
          version: 0.15.1
          args: |
            precompile --libc glibc --c-src-dir c_src --build-scripts-src-dir custom --plat linux/amd64

          # dagger call \
          #   precompile --libc glibc --c-src-dir c_src --build-scripts-src-dir custom --plat linux/amd64 \
          #   export --path output/ --allowParentDirPath
