name: precompile

on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and load
        uses: docker/build-push-action@v6
        with:
          context: ./custom
          platforms: linux/amd64,linux/arm64
          file: ./custom/Dockerfile.musl
          tags: pdfium-musl-builder
          tags: localhost:5000/gmile/pdfium-musl-builder:latest
      - run: |
          docker run \
            --workdir=/pdfium-build \
            --platform=linux/arm64 \
            --mount type=bind,source=$(realpath ./custom),target=/pdfium-build \
            pdfium-musl-builder \
            ./build-for-linux.sh linux-musl armv8-a 27.2
