name: precompile

on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v3
      - name: Hello
        uses: dagger/dagger-for-github@v6
        with:
          module: github.com/shykes/daggerverse/hello
          call: precompile --libc glibc --c-src-dir c_src --build-scripts-src-dir custom --plat linux/amd64

          # dagger call \
          #   precompile --libc glibc --c-src-dir c_src --build-scripts-src-dir custom --plat linux/amd64 \
          #   export --path output/ --allowParentDirPath
