name: precompile

on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: prod
    steps:
      - uses: actions/checkout@v3
      - run: docker build --platform=linux/amd64 --load --tag pdfium-musl-builder - < custom/Dockerfile.musl
      - run: |
          docker run \
            --workdir=/pdfium-build \
            --platform=linux/arm64 \
            --mount type=bind,source=$(pwd),target=/pdfium-build \
            pdfium-musl-builder \
            ./build-for-linux.sh linux-musl armv8-a 27.2
