name: precompile

on:
  push:
    tags:
      - 'v*'

jobs:
  linux:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        pdfium-tag:
          - chromium/6886
        abi:
          - glibc
          - musl
        platform:
          - linux/arm64
          - linux/amd64

    steps:
      - uses: actions/checkout@v3

      - run: mkdir output

      - name: Precompile
        uses: dagger/dagger-for-github@v7.0.3
        with:
          version: 0.15.1
          args: >-
            precompile
              --abi ${{ matrix.abi }}
              --platform-name ${{ matrix.platform }}
              --src-dir c_src
              --pdfium-tag ${{ matrix.pdfium-tag }}

            export
              --path output/precompiled.tar
              --allow-parent-dir-path
          engine-stop: false

      - name: Test
        uses: dagger/dagger-for-github@v7.0.3
        with:
          version: 0.15.1
          args: >-
            test
              --abi ${{ matrix.abi }}
              --platform-name ${{ matrix.platform }}
              --precompiled output/precompiled.tar

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: output/*.tar.gz
