name: precompile

# Call workflow manually

# TODO: make release verified
#
# TODO: have custom cc_precompiler according to rules here:
#
# TODO: rename pdfium-tag -> libpdfium-tag
#
# TODO: add hexpm release here
#
#       mix hex.publish package
#       mix hex.user auth
#       mix hex.publish package --yes --replace ???
#
# TODO: pack all of the above into a dagger script
#
# TODO: use build naming, e.g. 0.1.0+libpdfium.6889
#
# TODO: add tailscale to GH runners

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release-draft:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Create release draft
        uses: dagger/dagger-for-github@v7.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 0.15.1
          args: create-release --tag ${{ github.ref_name }} --draft=true --github-token GITHUB_TOKEN sync

  linux:
    runs-on: ubuntu-24.04

    needs: create-release-draft

    strategy:
      matrix:
        pdfium_tag:
          - chromium/6886
        abi:
          - glibc
          - musl
        platform:
          - linux/arm64
          - linux/amd64

    steps:
      - uses: actions/checkout@v3

      - name: Precompile
        uses: dagger/dagger-for-github@v7.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 0.15.1
          args: >-
            build-test-and-publish \
              --tag ${{ github.ref_name }} \
              --abi ${{ matrix.abi }} \
              --src-dir c_src \
              --platform-name ${{ matrix.platform }} \
              --pdfium-tag ${{ matrix.pdfium_tag }} \
              --github-token GITHUB_TOKEN \
              sync

  publish-release-draft:
    runs-on: ubuntu-24.04

    needs:
      - linux

    steps:
      - uses: actions/checkout@v3

      - name: Publish release draft
        uses: dagger/dagger-for-github@v7.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 0.15.1
          args: edit-release --tag ${{ github.ref_name }} --draft=false --github-token GITHUB_TOKEN sync
          engine-stop: false
