name: precompile

on:
  push:
    tags:
      - 'v*'

jobs:
  linux:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        abi:
          - glibc
          - musl
        platform:
          - linux/arm64
          - linux/amd64

    # TODO: would be nice to chain the "test" here before export
    steps:
      - uses: actions/checkout@v3
      - run: mkdir output
      - name: Precompile
        uses: dagger/dagger-for-github@v6
        with:
          version: 0.15.1
          args: >-
            precompile --abi ${{ matrix.abi }} --src-dir c_src --platform-name ${{ matrix.platform }}
            export --path output/ --allowParentDirPath
      # If this is about a tag - upload
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: output/*.tar.gz
