# Will be called by user with package-version to release the package

name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: Package version for the release
        required: false
        type: string

jobs:
  prepare:
    runs-on: ubuntu-24.04
    steps:
      - name: Run Dagger pipeline
        uses: dagger/dagger-for-github@v7.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 0.15.1
          args: >-
            prepare-release-pull-request \
              --base main \
              --package-version ${{ inputs.package_version }} \
              --actor ${{ github.actor }} \
              --github-token GITHUB_TOKEN
