name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - stable

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Release
        if: github.event.pull_request.merged == true
        uses: dagger/dagger-for-github@v7.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        with:
          version: 0.15.1
          args: >-
            create-release \
              --pr ${{ github.event.pull_request.number }} \
              --actor ${{ github.actor }} \
              --github-token GITHUB_TOKEN \
              --hex-api-key HEX_API_KEY
