name: Upload Random Files

on:
  workflow_dispatch:

jobs:
  create_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create random files
        run: |
          mkdir artifacts
          for i in {1..3}; do
            FILENAME="file_$(date +%s)_$i.txt"
            echo "Creating $FILENAME with some content" > "artifacts/$FILENAME"
            sleep 1  # ensure unique timestamps
          done
          # Create manifest
          ls artifacts/ > artifacts/manifest.txt

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: random-files
          path: artifacts/
