name: Update to latest libpdfium

on:
  workflow_dispatch:
  schedule:
    - cron: 0 13 * * 1

jobs:
  update-to-latest:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - id: check-latest-tag
        name: Check latest tag
        uses: dagger/dagger-for-github@v8.4.1
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          version: 0.20.6
          args: check-latest-tag --github-token GITHUB_TOKEN

      - name: Publish PR with version update
        if: ${{ fromJSON(steps.check-latest-tag.outputs.output).new_tag_available }}
        uses: dagger/dagger-for-github@v8.4.1
        with:
          version: 0.20.6
          args: >-
            prepare-release-pull-request \
              --base stable \
              --libpdfium-tag ${{ fromJSON(steps.check-latest-tag.outputs.output).tag }} \
              --actor 41898282+github-actions[bot] \
              --github-token GITHUB_TOKEN
