name: Workflow A

on:
  pull_request:
    types: [opened]

jobs:
  create-files:
    runs-on: ubuntu-latest
    steps:
      - name: Create files
        run: |
          echo "Content for file 1" > file1.txt
          echo "Content for file 2" > file2.txt
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pr-files
          path: |
            file1.txt
            file2.txt
